### PR TITLE
Extract development dependencies to the Gemfile

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR changes the way development dependencies are kept around: 

- Use the `group` functionality of Bundler
- This is something that becomes easier like this: Add the `pry` gem to the development group, with the `master` branch active
- Loosened the dependencies' versions
- _Removed_ the Gemfile.lock from the gem's repository (and: `git ignore Gemfile.lock`)

### CODE REVIEW

**Comment by duckinator** [comment]
I really don't like having dependencies split across two files. I also like having the Gemfile.lock specify exact versions, since how_is has a _massive_ dependency tree (despite only relying on 4 runtime gems directly), and it's gotten difficult to debug things before because of that.

I'd rather see _just_ pry added to the Gemfile, with a note saying why it's in the Gemfile to start with + under what conditions it should be removed.

**Comment by duckinator** [comment]
I'm not against having Gemfile.lock removed if you think it's unnecessary; that reasoning was just why I added it. I'm not sure if it was actually useful lol

**Comment by olleolleolle** [comment]
I'm sorry I left out any reasons to change this.

Here's _something_:

- Multi-platform, multi-version: people using JRuby for instance, maaaay want to use this gem, and for them, we _could_ go one step further and add the `ruby RUBY_VERSION` line to the Gemfile. That's the "version hinting" functionality which assists Bundler in finding gems suitable for currently used Ruby. When all this is in place, the CI matrix is ready to be expanded. 

Oh, and YES, we ought to keep the relevant version ranges in the Gemfile. That is much better. 

---

But, as you mentioned, the gain I wanted could be won by adding a line to the Gemfile and regenerating the lock file. A good code comment would help the reader with the "why" of that. (There's no `.ruby-version` file, is there? Which Ruby ought I be using to regenerate the lock file?)

**Comment by duckinator** [comment]
@olleolleolle losing the version information is bad. APIs _will_ change out from under you, and it always ends poorly.

I've got some recommendations below, but **I recommend making a new PR to supersede this one** given the number of differences.

A few things:

1. A thing I learned elsewhere is you can leave the deps in the gemspec and put things in the `:development` group in the Gemfile and it _works as expected_.
2. I only want to support actively-maintained versions of Ruby -- [currently that is 2.3+](https://www.ruby-lang.org/en/downloads/branches/), but that number should be updated whenever a version goes into security maintenance.

Given that, could you make a new PR that makes your Gemfile.lock changes + leaves the gemspec alone + changes the Gemfile to the following?:

```ruby
# frozen_string_literal: true

# how_is only supports Ruby versions receiving general bug fixes ("normal maintenance").
# This should be updated whenever a version goes into security maintenance.
# Ruby maintenance information: https://www.ruby-lang.org/en/downloads/branches/
ruby "~> 2.3"

source "https://rubygems.org"

# Specify your gem's dependencies in how_is.gemspec
gemspec

# TODO: move Pry back to gemspec, once a version is released that doesn't
#   rely on an ancient version of Slop.
# gemspecs can't handle git deps.
group :development do
  gem "pry", git: "https://github.com/pry/pry.git"
end
```

**Comment by olleolleolle** [comment]
Yeah I can!

**Comment by olleolleolle** [comment]
I'll close this issue when I have a replacement PR.

**Comment by duckinator** [comment]
👍

**Comment by duckinator** [comment]
oh, that's bullshit. it doesn't actually prevent you from merging the PR, even though it says "... that must be addressed before merging."

**Pull request closed without merging**
