### PR TITLE
[docs] YARD annotation for example

### PR DESCRIPTION
**Pull request by olleolleolle**
- this avoids a warning with yard-junk (the gem)

### CODE REVIEW

**Comment by duckinator** [comment]
@bundlerbot r+

**Comment by duckinator** [comment]
codeclimate failure is me failing to configure things right before; need to debug it.

**Comment by duckinator** [comment]
thanks for the PR! :3

**Comment by olleolleolle** [comment]
_Glad to provide_, and good to see you again.

**Pull request merged**
