### PR TITLE
Make CONFIG_FILE optional.

### LINKED ISSUE #41: Make CONFIG_FILE optional when using --config.
`how_is --config` should be equivalent to `how_is --config how_is.yml`.

Not sure how to do that with Slop.

### PR DESCRIPTION
**Pull request by duckinator**
Fixes #41.

### CODE REVIEW

**Comment by duckinator** [comment]
I DON'T UNDERSTAND WHY THIS BREAKS TESTS.

**Comment by olleolleolle** [comment]
Line 66 could be

```ruby
      if Pathname(options[:config]).file?
```

Or refer to some method that would validate the rightness of the given config file.

**Comment by duckinator** [comment]
So, what's happening is that passing `default: HowIs::CLI::DEFAULT_CONFIG_FILE` means that options[:config] is ALWAYS specified. However, what I need is to have a default value whenever --config has been specified.

That is,

`how_is --config` => has a default value
`how_is foo/bar` => no default value

**Comment by duckinator** [comment]
I can't find a way to do this, so I'm closing this PR.

**Pull request closed without merging**
