### PR TITLE
exe/how_is: Reinstate to_json, to_html

### LINKED ISSUE #149: Issue: report.html renders only #<HowIs:0x007fae56966700>
The `send("to_#{format}")` which was removed from the last commit made the `how_is` report.html look like this:

```
 ~ cat report.html
#<HowIs:0x007fae56966700>%
```

Perhaps there needs to be a `#to_s` on that class, or something?

Using the previous implementation (here with `public_send`) works:

```ruby
def save_files(reports)
  reports.each do |file, report|
    format = file.split('.').last

    File.open(file, 'w') do |f|
      f.write report.public_send("to_#{format}")
    end
  end
end
```

### PR DESCRIPTION
**Pull request by olleolleolle**
- Fixes #149 
  - Avoids using the [`format`](https://ruby-doc.org/core-2.4.0/Kernel.html#method-i-format) name
  - And then, reworked to ideas in #149 comments ✨ 😍

### CODE REVIEW

**Comment by duckinator** [comment]
Thanks for the PR! However, I'm not going to merge this because it turns out the issue is a bit deeper than that, and will need more work.

See https://github.com/how-is/how_is/issues/149#issuecomment-285918484 for more details.

Would you like to make the changes mentioned in that comment, or should I?

**Comment by olleolleolle** [comment]
@duckinator There!

**Comment by duckinator** [comment]
Looks good! I also found another bug while looking at this lol (#151). That problem existed before this PR, so I'm handling it separately.

Sorry about the delay getting to this, been dealing with a lot of health issues recently.

Thanks for the PR!

**Comment by olleolleolle** [comment]
Thank _you_ for being awesome.

**Pull request merged**
