### PR TITLE
README: Drop Gemnasium badge

### PR DESCRIPTION
**Pull request by olleolleolle**
*Hugs*. That service is defunct.

### CODE REVIEW

**Comment by duckinator** [comment]
... apparently travis-ci changed something that broke every build.

**Comment by duckinator** [comment]
looks like they added security restrictions for PRs without mentioning it anywhere. https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions

**Comment by duckinator** [comment]
bors try

**Comment by duckinator** [comment]
thanks for the PR, @olleolleolle, and sorry for all the comment noise lol

**Comment by olleolleolle** [comment]
No worries, I learned something.

**Pull request merged**
