### PR TITLE
Builds: a Travis CI API fetcher

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR tries to improve the `#commits` and the `#commit` methods for readability.

- Initialize the `@commit` Hash in the initializer
- Map directly on the result of the API call, inside a begin/end structure

(Eh. This PR is now a tentative feature implementation of the Travis CI API fetcher. Also. See #163)

- Add a class `Builds`, which has the same kind of scope as Contributions - it wants to present any metadata about (the duration of) CI builds

### CODE REVIEW

**Comment by olleolleolle** [comment]
The test failure is 

```
     NoMethodError:
       undefined method `debug' for Tessellator:Module
```

See https://gitlab.com/tessellator/tessellator-fetcher/merge_requests/4

**Comment by duckinator** [comment]
if you rebase off of master, that should be fixed, courtesy of #192. (thanks for the PR on tessellator-fetcher resolving that, btw!)

**Comment by duckinator** [comment]
Also,

1. could you update the issue title + initial comment to reflect what the PR is actually for?
2. could you not split the URL for `Contributions#compare_url`? I don't like URLs being split across multiple lines; if makes it less clear what's going on.

**Comment by duckinator** [comment]
@olleolleolle this looks really good! are you still working on it, or should I go ahead and merge it?

**Comment by olleolleolle** [comment]
Go ahead, it does what it claims to do.

**Comment by duckinator** [comment]
thanks! 🎉

**Pull request merged**
